function [R,G,B]=visualizeSpotMap(gSpotMapStack,bSpotMapStack, stack, varargin)
%% ========================================================================
%   Name: visualizeSpotMap
%   Version: 1.0 30th Apr. 2013
%   Author: Allison Wu
%   Command:
%   [R,G,B]=visualizeSpotMap(gSpotMapStack,bSpotMapStack, stack, sliceNumber*)
%   *Optional Input
%
%   Description:
%       - It takes in the spot maps generated by spotMapAndStats.m.
%       - Map the good spots and bad spots on max merged images (default).
%       - If a sliceNumber is specified, it will only map good spots and
%       bad spots on the specified slice.
%
%   Input required:
%       - gSpotMapStack: map of good spots generated by spotMapAndStats. It
%       is a 3D stack with only 1 and 0, 1 specifiying the location of
%       spot.
%       - bSpotMapStack: map of bad spots generated by spotMapAndStats
%       - stack: the corresponding segmented image stack.
%       
%   Update:
%       - 2013 May 25th: Revise the way it takes in the variable so that
%       the users can also visualize max-merged maps from a specified slice
%       to another. 
%       e.g. visualizeSpotMap(gSpotMapStack,bSpotMapStack,stack,14:17);
%            visualizes the spot map from slice 14 to slice 17.
%% ========================================================================
if isempty(gSpotMapStack)
    gSpotMapStack=zeros(size(stack));
end

if isempty(bSpotMapStack)
    bSpotMapStack=zeros(size(stack));
end

if isempty(varargin) % Max merged image if the slice is not specified
    slice=imscale(max(stack,[],3));
    slice(slice>1)=1;
    gSpotSlice=max(gSpotMapStack,[],3);
    bSpotSlice=max(bSpotMapStack,[],3);

else
    h=varargin{1};
    slice=imscale(max(stack(:,:,h),[],3));
    slice(slice>1)=1;
    gSpotSlice=max(gSpotMapStack(:,:,h),[],3);
    bSpotSlice=max(bSpotMapStack(:,:,h),[],3);
 
end
spotSlice=gSpotSlice+bSpotSlice;
slice=slice.*(~spotSlice);
R=slice+gSpotSlice;
G=slice;
B=slice+bSpotSlice;

imagesc(cat(3,R,G,B))

end